### PR TITLE
Update code to keep the python2 support

### LINKED ISSUE #6: Python 2 Setuptools warning
```
STEP 5: RUN mkdir /etc/ansible/ &&     echo -e '[local]\nlocalhost' > /etc/ansible/hosts &&     pip install ansible &&     pip uninstall -y pycrypto &&     yum erase -y python-crypto &&     yum install -y python-crypto python-paramiko &&     yum remove -y epel-release &&     yum clean all
cannot configure rootless cgroup using the cgroupfs manager
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:19: UserWarning: ************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release. Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
```

### PR DESCRIPTION
**Pull request by renanrodrigo**
Pin the pip version to guarantee compatibility and proper version of setuptools.
Also updates to ansible syntax.

Fix #6

### CODE REVIEW

**Review by StykMartin — APPROVED** [review]
Package list kinda killing readability but at least it brings performance

**Review by StykMartin — CHANGES_REQUESTED** [review]
Where is issue reference?

**Review by cbouchar — APPROVED** [review]

**Comment by duck-rh** [comment]
Ansible updates are much welcome but should really have been done in a separate PR.

**Comment by renanrodrigo** [comment]
Sorry for that. But upgrading pip has also changed the default ansible which is installed, and things like sudo or '|' broke in the change. I changed them to assure everything would be working.

**Review by StykMartin — APPROVED** [review]

**Pull request merged**
